language: elixir

matrix:
  include:
  - elixir: '1.12.2'
    otp_release: '21.0'
  - elixir: '1.12.2'
    otp_release: '24.3'

script:
  - make test
  - travis_wait 30 make dialyzer

services:
  - rabbitmq

sudo: required
